-- schema.sql
-- Scripts para criação das tabelas do projeto (PostgreSQL).
-- Compatível com as entidades JPA definidas no código.
--
-- A tabela de membros NÃO existe aqui porque os membros são gerenciados
-- exclusivamente pela API externa (members-api). O project-manager-api
-- armazena apenas os IDs dos membros (manager_id e member_id).

BEGIN;

-- projects
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    expected_end_date DATE NOT NULL,
    actual_end_date DATE,
    budget NUMERIC(19,2) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL,
    manager_id BIGINT NOT NULL,

    CONSTRAINT ck_projects_status
        CHECK (status IN (
            'EM_ANALISE',
            'ANALISE_REALIZADA',
            'ANALISE_APROVADA',
            'INICIADO',
            'PLANEJADO',
            'EM_ANDAMENTO',
            'ENCERRADO',
            'CANCELADO'
        ))
);

CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);
CREATE INDEX IF NOT EXISTS idx_projects_manager_id ON projects(manager_id);

-- project_members (IDs dos membros associados via API externa)
CREATE TABLE IF NOT EXISTS project_members (
    project_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,

    CONSTRAINT fk_project_members_project
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,

    CONSTRAINT pk_project_members PRIMARY KEY (project_id, member_id)
);

CREATE INDEX IF NOT EXISTS idx_project_members_member_id ON project_members(member_id);

COMMIT;
